#!/usr/bin/env sh

: ${SANDBOX_NAME:="sbx-0"}
: ${SANDBOX_NUMBER:="${SANDBOX_NAME##*-}"}
: ${SANDBOX_PATH:="/chroot/${SANDBOX_NAME}"}

setup_chroot() {
    mkdir -p \
        "${SANDBOX_PATH}/dev" \
        "${SANDBOX_PATH}/home" \
        "${SANDBOX_PATH}/tmp"

    chown nobody \
        "${SANDBOX_PATH}/home" \
        "${SANDBOX_PATH}/tmp"

    mknod -m 0666 "${SANDBOX_PATH}/dev/null" c 1 3
    mknod -m 0666 "${SANDBOX_PATH}/dev/urandom" c 1 9
}

setup_network() {
    local DEVICE="${SANDBOX_NAME//-/}"

    # Create a network namespace.
    ip netns add "$SANDBOX_NAME"

    # Create a bridge device on the host.
    ip link add br0 type bridge || true
    ip link set br0 up
    ip addr add "10.0.${SANDBOX_NUMBER}.1" dev br0
    ip route add "10.0.${SANDBOX_NUMBER}.0" dev br0

    # Create a veth pair on the host.
    ip link add "$DEVICE" type veth peer name veth
    ip link set "$DEVICE" master br0
    ip link set "$DEVICE" up

    # Move one end of the veth pair into the namespace.
    ip link set veth netns "$SANDBOX_NAME"
    ip netns exec "$SANDBOX_NAME" ip link set veth name eth0
    ip netns exec "$SANDBOX_NAME" ip link set eth0 up
    ip netns exec "$SANDBOX_NAME" ip link set lo up
    ip netns exec "$SANDBOX_NAME" ip addr add "10.0.${SANDBOX_NUMBER}.0/31" dev eth0
    ip netns exec "$SANDBOX_NAME" ip route add default via "10.0.${SANDBOX_NUMBER}.1" dev eth0
}

sandbox() {
    local CMD="$@"

    ip netns exec "$SANDBOX_NAME" su -s /bin/sh -c " \
        export HOME=/home
        unshare -r \
        chroot ${SANDBOX_PATH} \
        ${CMD}
    " nobody
}

if type "$1" | grep -q "function"; then "$1"; else sandbox "$@"; fi
