#!/usr/bin/env sh

: ${SANDBOX_NAMESPACE:="sbx-0"}
: ${SANDBOX_NUMBER:="${SANDBOX_NAMESPACE##*-}"}
: ${SANDBOX_PATH:="/chroot/${SANDBOX_NAMESPACE}"}
: ${SANDBOX_USERNAME:="nobody"}

setup_chroot() {
    adduser -s /sbin/nologin -D -H "$SANDBOX_USERNAME"

    mkdir -p \
        "${SANDBOX_PATH}/dev" \
        "${SANDBOX_PATH}/home" \
        "${SANDBOX_PATH}/proc" \
        "${SANDBOX_PATH}/tmp"

    chown -R "$SANDBOX_USERNAME" \
        "${SANDBOX_PATH}/home" \
        "${SANDBOX_PATH}/tmp"

    mknod -m 0666 "${SANDBOX_PATH}/dev/null" c 1 3
    mknod -m 0666 "${SANDBOX_PATH}/dev/urandom" c 1 9

    mount proc "${SANDBOX_PATH}/proc" -t proc
}

setup_network() {
    DEVICE="${SANDBOX_NAMESPACE//-/}"

    # Create a network namespace
    ip netns add "$SANDBOX_NAMESPACE"

    # Create a bridge device on the host
    ip link add br0 type bridge || true
    ip link set br0 up
    ip addr add "10.0.${SANDBOX_NUMBER}.1" dev br0
    ip route add "10.0.${SANDBOX_NUMBER}.0" dev br0

    # Create a veth pair on the host
    ip link add "$DEVICE" type veth peer name veth
    ip link set "$DEVICE" master br0
    ip link set "$DEVICE" up

    # Move one end of the veth pair into the namespace
    ip link set veth netns "$SANDBOX_NAMESPACE"
    ip netns exec "$SANDBOX_NAMESPACE" ip link set veth name eth0
    ip netns exec "$SANDBOX_NAMESPACE" ip link set eth0 up
    ip netns exec "$SANDBOX_NAMESPACE" ip link set lo up
    ip netns exec "$SANDBOX_NAMESPACE" ip addr add "10.0.${SANDBOX_NUMBER}.0/31" dev eth0
    ip netns exec "$SANDBOX_NAMESPACE" ip route add default via "10.0.${SANDBOX_NUMBER}.1" dev eth0
}

sandbox() {
    CMD="$@"

    ip netns exec "$SANDBOX_NAMESPACE" su -s /bin/sh -c " \
        export HOME=/home
        unshare -r \
        chroot ${SANDBOX_PATH} \
        ${CMD}
    " "$SANDBOX_USERNAME"
}

if type "$1" | grep -q "function"; then "$1"; else sandbox "$@"; fi
